pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
      version: '8.0.100-rc.1.23463.5'

- script: |
    dotnet tool restore
    dotnet run --project tests/tests.fsproj
  displayName: 'SAFE Template tests'